Velcro test First SandBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <inlineHelpText>Strategic Business Unit</inlineHelpText>
        <label>SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Personal Care</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Packaging</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Total Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/objects/Sample_Line__c.object
<CustomObject>
    <description>Sample line to generate a sample request listing</description>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sample_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sample Request</label>
        <referenceTo>Sample_Request__c</referenceTo>
        <relationshipLabel>Sample Lines</relationshipLabel>
        <relationshipName>Sample_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sample Line</label>
    <nameField>
        <displayFormat>SL-{000000}</displayFormat>
        <label>Samples Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Velcro test First SandBox/src/objects/Sample_Request__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sample Requests</relationshipLabel>
        <relationshipName>Sample_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Delivery_method__c</fullName>
        <label>Delivery method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UPS</fullName>
                </value>
                <value>
                    <fullName>VELCRO TRUCK</fullName>
                </value>
                <value>
                    <fullName>Courier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Region__c</fullName>
        <inlineHelpText>Pick the region where customer is located</inlineHelpText>
        <label>Request Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>CONSUMER</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_to_Country__c</fullName>
        <description>Country where the request will go</description>
        <inlineHelpText>Choose the country where the request will go</inlineHelpText>
        <label>Request to Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Request_Region__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>Spain</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <formula>TEXT(Opportunity__r.Opportunity_SBU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SBU</label>
        <type>Text</type>
    </fields>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Sample Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Velcro test First SandBox/src/classes/APAC_SampleLineHandlerTest.cls
@isTest
class APAC_SampleLineHandlerTest {
    static testMethod void test(){
    	Account a = new Account(Name = 'Burlington Acme',SBU__c='Transportation');
        insert a;
        Sample_Request__c sr = new Sample_Request__c(Customer__c=a.id,Request_Region__c='EMEA',Request_to_Country__c='Spain',
        		Delivery_method__c='UPS',CurrencyIsoCode='CNY');
        insert sr;
        Sample_Line__c line = new Sample_Line__c(Sample_Request__c=sr.id,Length__c=10,
        		Quantity__c=10,Estimated_Unit_Price_APAC__c=10,CurrencyIsoCode='CNY');
        insert line;
        delete line;
    }
}