Velcro test First SandBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Global Market Segments</description>
        <inlineHelpText>Global Market Segments</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive Seating</fullName>
                </value>
                <value>
                    <fullName>Automotive Interiors</fullName>
                </value>
                <value>
                    <fullName>Automotive All Other</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Mass Transit</fullName>
                </value>
                <value>
                    <fullName>Transportation Distributors</fullName>
                </value>
                <value>
                    <fullName>Diagnostics</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Surgical</fullName>
                </value>
                <value>
                    <fullName>Respiratory</fullName>
                </value>
                <value>
                    <fullName>Vascular</fullName>
                </value>
                <value>
                    <fullName>Ostomy</fullName>
                </value>
                <value>
                    <fullName>Contract Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Medical Distributors</fullName>
                </value>
                <value>
                    <fullName>Other (Small Applications)</fullName>
                </value>
                <value>
                    <fullName>Flexible Packaging</fullName>
                </value>
                <value>
                    <fullName>Rigid Packaging</fullName>
                </value>
                <value>
                    <fullName>Warehouse &amp; Logistics</fullName>
                </value>
                <value>
                    <fullName>Gift, Promotional &amp; Stationary</fullName>
                </value>
                <value>
                    <fullName>P&amp;MH Distributors</fullName>
                </value>
                <value>
                    <fullName>Other Packaging</fullName>
                </value>
                <value>
                    <fullName>Construction (Cable Management)</fullName>
                </value>
                <value>
                    <fullName>Building Envelope</fullName>
                </value>
                <value>
                    <fullName>Flooring</fullName>
                </value>
                <value>
                    <fullName>Renewable Energy</fullName>
                </value>
                <value>
                    <fullName>Tools &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Construction Distributors</fullName>
                </value>
                <value>
                    <fullName>Infant Care</fullName>
                </value>
                <value>
                    <fullName>Child Care</fullName>
                </value>
                <value>
                    <fullName>Feminine Care</fullName>
                </value>
                <value>
                    <fullName>Adult Care</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>Confirm what values should be in Org.</description>
        <inlineHelpText>Use the standard names ( VUSA, VAUS, VESA,VGMBH,VIF,VLTD, VCH ..)</inlineHelpText>
        <label>Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <inlineHelpText>Strategic Business Unit</inlineHelpText>
        <label>SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Personal Care</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Packaging</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Total Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer - accounts integrated with Oracle</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DR_Operating_Unit__c</fullName>
        <description>Depending on the value of the label &apos;Enable_DR_Oracle_Sync&apos; , if label is =1,  the formula will set it to a value to be synced with Oracle. If the label is not =&apos;1&apos;, then  formula will return  &apos;9999&apos;  and this will stop the sync with Oracle for DR.</description>
        <formula>IF  (($Label.Enable_DR_Oracle_Sync = &apos;1&apos;),
CASE(UPPER(Account.Org__c), &apos;VESA&apos;, &apos;485&apos;, &apos;VLTD&apos;, &apos;485&apos;, &apos;VGMBH&apos;, &apos;485&apos;, &apos;VIF&apos;, &apos;485&apos;, &apos;VEIT&apos;, &apos;485&apos;, 
&apos;APL&apos;,&apos;485&apos;,
&apos;ABE&apos;,&apos;485&apos;,
&apos;ALFTXBE&apos;,&apos;485&apos;,
&apos;ALFTXDE&apos;,&apos;485&apos;,
&apos;ALFTXES&apos;,&apos;485&apos;,
&apos;ALFTXFR&apos;,&apos;485&apos;,
&apos;ALFTXGV&apos;,&apos;485&apos;,
&apos;ALFTXNL&apos;,&apos;485&apos;,
&apos;ALFTXPL&apos;,&apos;485&apos;,
&apos;ALFTXUK&apos;,&apos;485&apos;,
&apos;VCAN&apos;, &apos;89&apos;, 
&apos;VUSA&apos;, &apos;89&apos;,
&apos;0&apos;
),&apos;9999&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DR Operating Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pilot_Runs__c</fullName>
        <label>Pilot Runs?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>&gt;1</fullName>
                </value>
                <value>
                    <fullName>&gt;3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Quality_Requirements_Standard__c</fullName>
        <label>Product Quality Requirements Standard?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Require_Standard_Processes__c</fullName>
        <label>Product Require Standard Processes?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Requires_Standard_Material__c</fullName>
        <label>Product Requires Standard Material?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#999999</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submit</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <color>#FF0000</color>
                </value>
                <value>
                    <fullName>DR-Downloaded</fullName>
                    <color>#33FFFF</color>
                </value>
                <value>
                    <fullName>DR-Opened</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>DR-Completed</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Engineering Complete</fullName>
                    <color>#33CC00</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <businessProcess>Customer Sales Process</businessProcess>
        <description>AMERICAS: Sales process for Standard Opportunities</description>
        <label>Standard Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/classes/testCheck_Opportunity.cls
@isTest

public class testCheck_Opportunity {

 static testMethod void LCUnitTest1()
  {
    Account newAcc = new Account();
    newAcc.name='test Account 1';
    newAcc.Org__c='VUSA';
    newAcc.SBU__c='Transportation';
    newAcc.Customer_Category__c='Automotive Seating';
    Id RecordTypeIdaccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('EMEA Customer').getRecordTypeId();
    newAcc.RecordTypeId= RecordTypeIdaccount;
    insert newAcc;
    System.assertEquals('VUSA',newAcc.Org__c);
    
    Opportunity o1=new Opportunity(); 
    o1.Name = 'Test Opp1';
    List <User> user_list = [SELECT Id  FROM User where Username like 'velcro.com'];  
    for (User user_rec : user_list)
    {
      o1.ownerid = user_rec.Id;    
    }
    System.debug('Acc name: ' + newAcc.name);
       
    o1.accountid= newAcc.Id;
    o1.closeDate= system.today(); 
    o1.Request_Status__c= 'Draft';    
    o1.StageName='Developing';
    o1.Type='Existing Business';
    o1.Amount=2;
    o1.Probability=60;
    Id RecordTypeIdOpp = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('C-EMEA Sales Opportunity').getRecordTypeId();
    o1.RecordTypeId= RecordTypeIdOpp;
    insert o1;

    System.debug('Opp:'+ o1.Name+' | '+o1.StageName+ '|  DR Org:'+ o1.DR_Operating_Unit__c );
    System.assertEquals('Draft',o1.Request_Status__c);
    
    List <Opportunity> oppList = [SELECT DR_Operating_Unit__c  FROM Opportunity where ID =  :o1.Id  ];  
    for ( Opportunity opp :oppList)
    {
        System.assertEquals('9999',opp.DR_Operating_Unit__c);
    }
    
    // formula field: will fail ...  System.assertEquals('485',o1.DR_Operating_Unit__c);
    
    Blob picture = Blob.valueOf('12345');
    Attachment a1 = new Attachment (ParentId = o1.Id,Body = picture,ContentType = 'text',Name = 'attach1.txt');
    Attachment a2 = new Attachment (ParentId = o1.Id,Body = picture,ContentType = 'text',Name = 'attach2.txt');
    insert a1; 
    insert a2;
    System.debug('Attachemnt id: '+ a1.Id + ' '+ a1.Name);
    System.debug('Attachemnt id: '+ a1.Id + ' '+ a1.Name);
    //Attachment[] lstAt = new List<Attachment>{a1,a2};
    //insert lstAt;
    o1.Request_Status__c = 'Approved'; 
    newAcc.Org__c='VESA';
    update o1;
       
    
  }


  static testMethod void LCUnitTest2()
  {
    Account newAcc = new Account();
    newAcc.name='test Account 2';
    newAcc.Org__c='VESA';
    newAcc.SBU__c='Transportation';
    newAcc.Customer_Category__c='Automotive Seating';
    Id RecordTypeIdaccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('EMEA Customer').getRecordTypeId();
    newAcc.RecordTypeId= RecordTypeIdaccount;
    insert newAcc;
    System.assertEquals('VESA',newAcc.Org__c);
    
    Opportunity o1=new Opportunity(); 
    o1.Name = 'Test Opp3';
    List <User> user_list = [SELECT Id  FROM User where Username like 'velcro.com'];  
    for (User user_rec : user_list)
    {
      o1.ownerid = user_rec.Id;    
    }
    System.debug('Acc name: ' + newAcc.name);
       
    o1.accountid= newAcc.Id;
    o1.closeDate= system.today(); 
    o1.Request_Status__c= 'Draft';    
    o1.StageName='Qualifying';
    o1.Type='New Business';
    o1.Amount=1;
    o1.Probability=40;
    Id RecordTypeIdOpp = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('C-EMEA Sales Opportunity').getRecordTypeId();
    o1.RecordTypeId= RecordTypeIdOpp;
    insert o1;

    System.debug('Opp:'+ o1.Name+' | '+o1.StageName+ '|  DR Org:'+ o1.DR_Operating_Unit__c );
    System.assertEquals('Draft',o1.Request_Status__c);
    
    List <Opportunity> oppList = [SELECT DR_Operating_Unit__c  FROM Opportunity where ID =  :o1.Id  ];  
    for ( Opportunity opp :oppList)
    {
        System.assertEquals('9999',opp.DR_Operating_Unit__c);
    }
    
    // formula field: will fail ...  System.assertEquals('485',o1.DR_Operating_Unit__c);
    
    Blob picture = Blob.valueOf('12345');
    Attachment a1 = new Attachment (ParentId = o1.Id,Body = picture,ContentType = 'text',Name = 'attach1.txt');
    Attachment a2 = new Attachment (ParentId = o1.Id,Body = picture,ContentType = 'text',Name = 'attach2.txt');
    insert a1; 
    insert a2;
    System.debug('Attachemnt id: '+ a1.Id + ' '+ a1.Name);
    System.debug('Attachemnt id: '+ a1.Id + ' '+ a1.Name);
    //Attachment[] lstAt = new List<Attachment>{a1,a2};
    //insert lstAt;
    o1.Request_Status__c = 'Approved'; 
    update o1;
    newAcc.Org__c='VUSA';
    update o1;
       
    
  } 
  
  static testMethod void testCloneOpp()  {
  	
  	Account newAcc = new Account();
    newAcc.name='test Account 2';
    newAcc.Org__c='VESA';
    newAcc.SBU__c='Transportation';
    newAcc.Customer_Category__c='Automotive Seating';
    Id RecordTypeIdaccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('EMEA Customer').getRecordTypeId();
    newAcc.RecordTypeId= RecordTypeIdaccount;
    insert newAcc;
    
    Opportunity o1=new Opportunity(); 
    o1.Name = 'Test Opp3';
    List <User> user_list = [SELECT Id  FROM User where Username like 'velcro.com'];  
    for (User user_rec : user_list)
    {
      o1.ownerid = user_rec.Id;    
    }
    System.debug('Acc name: ' + newAcc.name);
       
    o1.accountid= newAcc.Id;
    o1.closeDate= system.today(); 
    o1.Request_Status__c= 'Draft';    
    o1.StageName='Qualifying';
    o1.Type='New Business';
    o1.Amount=1;
    o1.Probability=40;
    Id RecordTypeIdOpp = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('C-EMEA Sales Opportunity').getRecordTypeId();
    o1.RecordTypeId= RecordTypeIdOpp;
    insert o1;
    
    
    String oldId= o1.Id;
    String Newname= o1.Name; 
    
     //clone1 = new CloneOpportunity();
    String ret= CloneOpportunity.getCloneOpp( oldId,  NewName);
    o1.Name = 'Test Cloned Child';
  	CloneOpportunity.getCloneOpp(ret, o1.Name+' clone');
  
  }
  
 //*** TestSchedule Class

public static void  testschedule() {

    Account newAcc = new Account();
    newAcc.name='test Account 2';
    newAcc.Org__c='VESA';
    newAcc.SBU__c='Transportation';
    newAcc.Customer_Category__c='Automotive Seating';
    Id RecordTypeIdaccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('EMEA Customer').getRecordTypeId();
    newAcc.RecordTypeId= RecordTypeIdaccount;
    insert newAcc;
    
    Opportunity o1=new Opportunity(); 
    o1.Name = 'Test Opp3';
    List <User> user_list = [SELECT Id  FROM User where Username like 'velcro.com'];  
    for (User user_rec : user_list)
    {
      o1.ownerid = user_rec.Id;    
    }
    System.debug('Acc name: ' + newAcc.name);
       
    o1.accountid= newAcc.Id;
    o1.closeDate= system.today(); 
    o1.Request_Status__c= 'Draft';    
    o1.StageName='Qualifying';
    o1.Type='New Business';
    o1.Amount=1;
    o1.Probability=40;
    o1.Quote__c=true;
    o1.Product_Require_Standard_Processes__c= 'YES';
    o1.Product_Requires_Standard_Material__c= 'YES';
    o1.Product_Quality_Requirements_Standard__c='YES';
    o1.Pilot_Runs__c='0';
    
    Id RecordTypeIdOpp = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('D-SPD Request').getRecordTypeId();
    o1.RecordTypeId= RecordTypeIdOpp;
    insert o1;
    
    
    
 Test.StartTest();
    // Create an approval request for the opportunity
	Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
	req1.setComments('Submitting opportunity for approval.');
	req1.setObjectId(o1.Id);
	// Submit the approval request for the account
    Approval.ProcessResult result = Approval.process(req1);
	// change the assigned approver
	Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
	req2.setComments('Reassigning request.');
	req2.setAction('Reassign');
	req2.setNextApproverIds(new Id[] { o1.ownerid} );
 	//*** throw the scheduler 
 	DRCheckAssignments reminder = new DRCheckAssignments();
	// Run every 30 minutes
 	String sch = '0 30 * * * ?';
	String jobID = System.schedule('EMEA DR Check Reassignments', sch, reminder);
 
 
Test.stopTest();

}
  
  
  
  
}