Velcro test First SandBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Org__c</fullName>
        <description>Confirm what values should be in Org.</description>
        <inlineHelpText>Use the standard names ( VUSA, VAUS, VESA,VGMBH,VIF,VLTD, VCH ..)</inlineHelpText>
        <label>Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#999999</color>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submit</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                    <color>#FFCC66</color>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <color>#FF0000</color>
                </value>
                <value>
                    <fullName>DR-Downloaded</fullName>
                    <color>#33FFFF</color>
                </value>
                <value>
                    <fullName>DR-Opened</fullName>
                    <color>#FFCC33</color>
                </value>
                <value>
                    <fullName>DR-Completed</fullName>
                    <color>#33CC00</color>
                </value>
                <value>
                    <fullName>Engineering Complete</fullName>
                    <color>#33CC00</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/classes/UnitTest_Check_Opportunity.cls
@isTest

Private Class UnitTest_Check_Opportunity {
 
  static testMethod void LCUnitTest()
  {
    Opportunity o1=new Opportunity(); 
    o1.Name='Test Opp1'; 
    List <User> user_list = [SELECT Id  FROM User where Email='rfontcuberta@velcro.com'];  
    for (User user_rec : user_list)
    {
      o1.ownerid = user_rec.Id;    
    }
    List <Account> account_list = [SELECT Id FROM Account where org__c = 'VESA' LIMIT 1];    
    for (Account account_rec : account_list)
    {
      o1.accountid = account_rec.Id;
    }    
    o1.closeDate=date.today(); 
    o1.Request_Status__c = 'Approved';    
    o1.StageName='Draft';
    o1.Probability=70;
    insert o1;  
  } 

  static testMethod void LCUnitTest2()
  {
    Opportunity o1=new Opportunity(); 
    o1.Name='Test Opp2'; 
    List <User> user_list = [SELECT Id  FROM User where Email='rfontcuberta@velcro.com'];  
    for (User user_rec : user_list)
    {
      o1.ownerid = user_rec.Id;    
    }
    List <Account> account_list = [SELECT Id FROM Account where org__c = 'VESA' LIMIT 1];    
    for (Account account_rec : account_list)
    {
      o1.accountid = account_rec.Id;
    }    
    o1.closeDate=date.today(); 
    o1.Request_Status__c = 'Approved';    
    o1.StageName='Draft';
    o1.Probability=70;
    insert o1;  
    Blob picture = Blob.valueOf('');
    Attachment a1 = new Attachment (ParentId = o1.id,Body = picture,ContentType = 'image/jpg',Name = 'VehiclePicture');
    Attachment a2 = new Attachment (ParentId = o1.id,Body = picture,ContentType = 'image/jpg',Name = 'VehiclePicture');
    Attachment[] lstAt = new List<Attachment>{a1,a2};
    insert lstAt;
  } 

  static testMethod void LCUnitTest3()
  {
    Opportunity o1=new Opportunity(); 
    o1.Name = 'Test Opp3';
    List <User> user_list = [SELECT Id  FROM User where Email='rfontcuberta@velcro.com'];  
    for (User user_rec : user_list)
    {
      o1.ownerid = user_rec.Id;    
    }
    List <Account> account_list = [SELECT Id FROM Account where org__c = 'VESA' LIMIT 1];    
    for (Account account_rec : account_list)
    {
      o1.accountid = account_rec.Id;
    }    
    o1.closeDate=date.today(); 
    o1.Request_Status__c = 'Draft';    
    o1.StageName='Draft';
    o1.Probability=70;
    insert o1;  
  } 
}