Velcro test First SandBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Global Market Segments</description>
        <inlineHelpText>Global Market Segments</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive Seating</fullName>
                </value>
                <value>
                    <fullName>Automotive Interiors</fullName>
                </value>
                <value>
                    <fullName>Automotive All Other</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Mass Transit</fullName>
                </value>
                <value>
                    <fullName>Transportation Distributors</fullName>
                </value>
                <value>
                    <fullName>Diagnostics</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Surgical</fullName>
                </value>
                <value>
                    <fullName>Respiratory</fullName>
                </value>
                <value>
                    <fullName>Vascular</fullName>
                </value>
                <value>
                    <fullName>Ostomy</fullName>
                </value>
                <value>
                    <fullName>Contract Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Medical Distributors</fullName>
                </value>
                <value>
                    <fullName>Other (Small Applications)</fullName>
                </value>
                <value>
                    <fullName>Flexible Packaging</fullName>
                </value>
                <value>
                    <fullName>Rigid Packaging</fullName>
                </value>
                <value>
                    <fullName>Warehouse &amp; Logistics</fullName>
                </value>
                <value>
                    <fullName>Gift, Promotional &amp; Stationary</fullName>
                </value>
                <value>
                    <fullName>P&amp;MH Distributors</fullName>
                </value>
                <value>
                    <fullName>Other Packaging</fullName>
                </value>
                <value>
                    <fullName>Construction (Cable Management)</fullName>
                </value>
                <value>
                    <fullName>Building Envelope</fullName>
                </value>
                <value>
                    <fullName>Flooring</fullName>
                </value>
                <value>
                    <fullName>Renewable Energy</fullName>
                </value>
                <value>
                    <fullName>Tools &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Construction Distributors</fullName>
                </value>
                <value>
                    <fullName>Infant Care</fullName>
                </value>
                <value>
                    <fullName>Child Care</fullName>
                </value>
                <value>
                    <fullName>Feminine Care</fullName>
                </value>
                <value>
                    <fullName>Adult Care</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>Confirm what values should be in Org.</description>
        <inlineHelpText>Use the standard names ( VUSA, VAUS, VESA,VGMBH,VIF,VLTD, VCH ..)</inlineHelpText>
        <label>Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <inlineHelpText>Strategic Business Unit</inlineHelpText>
        <label>SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Personal Care</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Packaging</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Total Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>PO_Number__c</fullName>
        <label>PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quality_Contact__c</fullName>
        <label>Quality Contact</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Quality_Issue_Plant__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alejandro Mirazo</fullName>
                </value>
                <value>
                    <fullName>Ben Tarazon</fullName>
                </value>
                <value>
                    <fullName>Jerome Deguzman</fullName>
                </value>
                <value>
                    <fullName>Mike Morrison</fullName>
                </value>
                <value>
                    <fullName>Stephen Olden</fullName>
                </value>
                <value>
                    <fullName>Steve Olden</fullName>
                </value>
                <value>
                    <fullName>Steve Veilleux</fullName>
                </value>
                <value>
                    <fullName>Toni Chaput</fullName>
                </value>
                <value>
                    <fullName>Victor Garcia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quality_Issue_Plant__c</fullName>
        <label>Quality Issue Plant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MHT</fullName>
                </value>
                <value>
                    <fullName>SW</fullName>
                </value>
                <value>
                    <fullName>VAP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <label>SBU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Packaging</fullName>
                </value>
                <value>
                    <fullName>Personal Care</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SO_Number__c</fullName>
        <label>SO Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total Dollar Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UOM__c</fullName>
        <label>UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yards</fullName>
                </value>
                <value>
                    <fullName>Feet</fullName>
                </value>
                <value>
                    <fullName>Meter</fullName>
                </value>
                <value>
                    <fullName>Rolls</fullName>
                </value>
                <value>
                    <fullName>Pieces</fullName>
                </value>
                <value>
                    <fullName>Square meters</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/classes/TestCreateOppty.cls
@isTest
public class TestCreateOppty {
    public static testMethod void newOpptyValid(){
        Account a = new Account();
         a.Name='Burlington Acme';
		 a.BillingStreet='street';
		 a.BillingPostalCode='08020';
		 a.BillingCity='Manchester';
		 a.BillingCountry='United States';
		 a.SBU__c='Construction';
		 a.Org__c='VUSA';
		 a.Customer_Category__c='Automotive Seating';
		insert a;
        Case c = new Case(AccountId = a.Id);
           
         c.SBU__c='Industrial';
         c.Quality_Issue_Plant__c='VAP';
         c.Quality_Contact__c='Ben Tarazon';
         c.UOM__c='Meter';
         c.Total__c= 1;
         //c.PO_Number__c='1';
         //c.SO_Number__c='1';
         
        insert c;
             
        String oppName = 'Burlington Acme 1000 TVs';
        
        List<Opportunity> lob = [SELECT Name, AccountId, StageName, CloseDate From Opportunity];
        System.assertEquals(0, lob.size());
        CreateOppty.newOppty(oppName, c.id);
        List<Opportunity> lo = [SELECT Name, AccountId, StageName, CloseDate From Opportunity];
        System.assertEquals(1, lo.size());
        System.assertEquals(lo[0].Name, oppName);
        System.assertEquals(lo[0].AccountId, a.Id);
        System.assertEquals(lo[0].StageName, 'Perception Analysis');
        System.assertEquals(lo[0].CloseDate, Date.today().addMonths(1));
    }
}