Velcro test First SandBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Category__c</fullName>
        <description>Global Market Segments</description>
        <inlineHelpText>Global Market Segments</inlineHelpText>
        <label>Customer Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBU__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Automotive Seating</fullName>
                </value>
                <value>
                    <fullName>Automotive Interiors</fullName>
                </value>
                <value>
                    <fullName>Automotive All Other</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Mass Transit</fullName>
                </value>
                <value>
                    <fullName>Transportation Distributors</fullName>
                </value>
                <value>
                    <fullName>Diagnostics</fullName>
                </value>
                <value>
                    <fullName>Orthopedics</fullName>
                </value>
                <value>
                    <fullName>Surgical</fullName>
                </value>
                <value>
                    <fullName>Respiratory</fullName>
                </value>
                <value>
                    <fullName>Vascular</fullName>
                </value>
                <value>
                    <fullName>Ostomy</fullName>
                </value>
                <value>
                    <fullName>Contract Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Medical Distributors</fullName>
                </value>
                <value>
                    <fullName>Other (Small Applications)</fullName>
                </value>
                <value>
                    <fullName>Flexible Packaging</fullName>
                </value>
                <value>
                    <fullName>Rigid Packaging</fullName>
                </value>
                <value>
                    <fullName>Warehouse &amp; Logistics</fullName>
                </value>
                <value>
                    <fullName>Gift, Promotional &amp; Stationary</fullName>
                </value>
                <value>
                    <fullName>P&amp;MH Distributors</fullName>
                </value>
                <value>
                    <fullName>Other Packaging</fullName>
                </value>
                <value>
                    <fullName>Construction (Cable Management)</fullName>
                </value>
                <value>
                    <fullName>Building Envelope</fullName>
                </value>
                <value>
                    <fullName>Flooring</fullName>
                </value>
                <value>
                    <fullName>Renewable Energy</fullName>
                </value>
                <value>
                    <fullName>Tools &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Construction Distributors</fullName>
                </value>
                <value>
                    <fullName>Infant Care</fullName>
                </value>
                <value>
                    <fullName>Child Care</fullName>
                </value>
                <value>
                    <fullName>Feminine Care</fullName>
                </value>
                <value>
                    <fullName>Adult Care</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>Confirm what values should be in Org.</description>
        <inlineHelpText>Use the standard names ( VUSA, VAUS, VESA,VGMBH,VIF,VLTD, VCH ..)</inlineHelpText>
        <label>Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBU__c</fullName>
        <inlineHelpText>Strategic Business Unit</inlineHelpText>
        <label>SBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Personal Care</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Packaging</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Total Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/classes/TestAccountDataSync.cls
@isTest

//*********************************************************************************************//
//* Class Name: TestAccountDataSync *//
//* Description : Test class used for Triggers updateing Account Data *//
//* Creation Date: 13-Sept-2018 *//
//*-------------------------------------------------------------------------------------------*//
//* History:                                        *//
//*********************************************************************************************// 


public class TestAccountDataSync {
 
  static testMethod void AccUnitTest1()
  {
  	
  	Account a = new Account(Name='Class Test Account',SBU__c='Industrial',Phone='931234567',Fax='939876543',Website='https://velcro.com');
  	a.Org__c='VUSA';
    a.SBU__c='Transportation';
    a.Customer_Category__c='Automotive Seating';
    insert a;
    a.Phone=null;
    a.Fax= null ;
    a.Website=null;
    update a;   // this should throw the account update trigger 
    
  	  	
  }
  
}