Velcro test First SandBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Actual_YTD_Gross_Sales__c</fullName>
        <inlineHelpText>Actual YTD Gross Sales from Oracle</inlineHelpText>
        <label>Actual YTD Gross Sales</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Budget__c</fullName>
        <inlineHelpText>Gross Budget from Oracle</inlineHelpText>
        <label>Gross Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/classes/LeadsNearbyMe.cls
global with sharing class LeadsNearbyMe {

public Lead leads{get; set;}
public Account accounts{get; set;}


@RemoteAction
   global static List<Lead> getNearbyLeads(String lat, String lon, String dist ) {

        if(lat == null || lon == null || lat.equals('') || lon.equals('')) {
            lat = '40.416775';
            lon = '-3.703790';
            //madrid 
        }

        String queryString =
            'SELECT Id, Name, Longitude, Latitude, ' +
            'Street, City,State,Country, PostalCode ' +
            'FROM Lead ' +
            'WHERE DISTANCE( Address, GEOLOCATION('+ lat+ ' ,'+ lon +'),\'km\')< '+ dist +' '+
            'LIMIT 500';
        return(database.Query(queryString));
    }


@RemoteAction
   global static List<Account> getNearbyAccounts(String lat, String lon, String dist ) {

        if(lat == null || lon == null || lat.equals('') || lon.equals('')) {
            lat = '40.416775';
            lon = '-3.703790';
            //madrid 
        }

        String queryString =
            'SELECT Id, Name, BillingLongitude, BillingLatitude, Phone ,BillingStreet, BillingCity ,Actual_YTD_Gross_Sales__c,Gross_Budget__c   ' +
            'FROM Account ' +
            'WHERE DISTANCE( BillingAddress, GEOLOCATION('+ lat+ ' ,'+ lon +'),\'km\')< '+ dist +' '+
            'LIMIT 500';
        return(database.Query(queryString));
    }
}