Velcro test First SandBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quote</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Velcro test First SandBox/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language of the  quote template</description>
        <inlineHelpText>Choose the language used to generate the quote according to the customer preferences.</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>EN</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>PL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Velcro test First SandBox/src/objects/Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Minimun_Order_Quantity__c</fullName>
        <description>Minimun_Order_Quantity</description>
        <inlineHelpText>Minimun_Order_Quantity</inlineHelpText>
        <label>Minimun Order Quantity</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Units_of_measure__c</fullName>
        <label>Units of measure</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Feet</fullName>
                </value>
                <value>
                    <fullName>Inches</fullName>
                </value>
                <value>
                    <fullName>Meters</fullName>
                </value>
                <value>
                    <fullName>Pcs</fullName>
                </value>
                <value>
                    <fullName>Roll</fullName>
                </value>
                <value>
                    <fullName>Sets</fullName>
                </value>
                <value>
                    <fullName>Sq Meters</fullName>
                </value>
                <value>
                    <fullName>Sq Yards</fullName>
                </value>
                <value>
                    <fullName>Yards</fullName>
                </value>
                <value>
                    <fullName>Bag</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{00000000}</displayFormat>
        <label>Quote Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Velcro test First SandBox/src/classes/Test_QuoteLinesList.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 */
 
@isTest
private class Test_QuoteLinesList {

 static testMethod void QuoteLinesUnitTest() {
 String Lang='EN';
 String Option='0';
 String result='';
 Quote quo = new Quote();
 opportunity opp= new Opportunity();
 opp.Name='test opp';
 opp.closeDate=date.today(); 
 opp.StageName='Draft'; 
 insert opp;
 system.debug('opp:' +opp.Id)  ;  
 
 if (opp!=null)
  {
 quo.Name='Test quote';
 quo.OpportunityId= opp.Id;
 quo.Language__c='EN'; 
 //quo.recordTypeId= Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Quote').getRecordTypeId();
 insert quo;
  }
 else system.debug('opp is null')  ;  
   
   
  if (quo!=null){
  	
        
 system.debug('quote:' +quo.Id)  ;  
  
  Quote_line__c qline= new Quote_line__c();
  qline.Description__c='desc';
  qline.Minimun_Order_Quantity__c=100;
  qline.Price__c=1;
  qline.Product_Code__c='123';
  qline.quote__c= quo.Id;
  qline.Units_of_measure__c='Roll';
  
  insert qline;
  system.debug('quote line:' +qline.Id)  ; 
  } 
  try{  
  ApexPages.StandardController sc = new ApexPages.StandardController(quo);
  QuoteLinesListController Qlines= new QuoteLinesListController(sc);
  
  //Qlines.addCount=1;
  Qlines.QuoteLinesExisting();
  Qlines.SetDelPos(1);
  Qlines.delWrapper();
  } catch (exception e) {
    system.debug('quote 1 ha petat')  ;
  }
  try {
  ApexPages.StandardController sc2 = new ApexPages.StandardController(quo);
  QuoteLinesListController Qlines2= new QuoteLinesListController(sc2);
  
  Qlines2.QuoteLinesExisting();
  Qlines2.SetaddCount(1);
  Qlines2.addRows();
  Qlines2.save();
  } catch (exception e) {
    system.debug('quote 2 ha petat')  ;
  }
  
  
        
    }
}