Velcro test First SandBox/src/objects/Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <description>Lead time, in working days</description>
        <inlineHelpText>Lead time, in working days</inlineHelpText>
        <label>Lead Time</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minimun_Order_Quantity__c</fullName>
        <description>Minimun_Order_Quantity</description>
        <inlineHelpText>Minimun_Order_Quantity</inlineHelpText>
        <label>Minimun Order Quantity</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Presented__c</fullName>
        <description>Presentation of the product ( boxes, pallets, rolls..)</description>
        <inlineHelpText>Presentation of the product ( boxes, pallets, rolls..)</inlineHelpText>
        <label>Presented</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Units_of_measure__c</fullName>
        <label>Units of measure</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Feet</fullName>
                </value>
                <value>
                    <fullName>Inches</fullName>
                </value>
                <value>
                    <fullName>Meters</fullName>
                </value>
                <value>
                    <fullName>Pcs</fullName>
                </value>
                <value>
                    <fullName>Roll</fullName>
                </value>
                <value>
                    <fullName>Sets</fullName>
                </value>
                <value>
                    <fullName>Sq Meters</fullName>
                </value>
                <value>
                    <fullName>Sq Yards</fullName>
                </value>
                <value>
                    <fullName>Yards</fullName>
                </value>
                <value>
                    <fullName>Bag</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{00000000}</displayFormat>
        <label>Quote Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Velcro test First SandBox/src/classes/QuoteLinesListController.cls
public with sharing class QuoteLinesListController 

{
 public List<QuoteLinesWrapper> wrappers {get; set;}
 public static Integer toDelIdent {get; set;}
 public static Integer addCount {get; set;}
 private Integer nextIdent=0;
 public String parentId;
  private final Quote quo;
 
 public QuoteLinesListController(ApexPages.StandardController stdController)
 {
  
  this.quo= (Quote)stdController.getRecord();
  
  parentId = System.currentPagereference().getParameters().get('Quoteid');	 
  parentId= quo.Id;
  wrappers=new List<QuoteLinesWrapper>();
  QuoteLinesExisting();
  
  for (Integer idx=0; idx<1; idx++)
  {
  // wrappers.add(new QuoteLinesWrapper(nextIdent++,parentId));
  }
 }

 public void SetDelPos(Integer pos)
 {
 	 toDelIdent=pos;
 }  
 public void SetaddCount (Integer addc)
 {
 	 addCount=addc;
 }  
 
 
 public void delWrapper()
 {
  Integer toDelPos=-1;
  for (Integer idx=0; idx<wrappers.size(); idx++)
  {
   if (wrappers[idx].ident==toDelIdent)
   {
    toDelPos=idx;
   }
  }
   
  if (-1!=toDelPos)
  {
   delete wrappers[toDelpos].quol;	
   wrappers.remove(toDelPos);
  }
 }
  
 public void addRows()
 {
  	 
  for (Integer idx=0; idx<addCount; idx++)
  {
   wrappers.add(new QuoteLinesWrapper(nextIdent++,parentId));
  }
 }
  
 public PageReference save()
 {
  List<Quote_Line__c> quols=new List<Quote_Line__c>();
  for (QuoteLinesWrapper wrap : wrappers)
  {
   quols.add(wrap.quol);
  }
   
  upsert quols;
   
  // return new PageReference('/' + parentId);
  return null;
   
 }
  
 public void QuoteLinesExisting() {
  	List<Quote_Line__c> existingQuoteLines= [SELECT Id,Description__c,Price__c,Product_Code__c,Minimun_Order_Quantity__c,Units_of_measure__c,Presented__c,Lead_Time__c, quote__c from Quote_line__c WHERE quote__c = :parentId ORDER BY Name];	
  	for (Quote_Line__c quo :existingQuoteLines ) {
  	   	wrappers.add(new QuoteLinesWrapper(nextIdent++, quo));
  	   }
  	}   
  
  
 public with sharing class QuoteLinesWrapper
 {
  public Quote_Line__c quol    {get; private set;}
  public Integer ident {get; private set;}
   
  public QuoteLinesWrapper(Integer inIdent, Quote_Line__c quoteLine )
   {
   ident=inIdent;
   quol=quoteLine;
   }
 
  public QuoteLinesWrapper(Integer inIdent, String parentId )
  {
   ident=inIdent;
   quol=new Quote_Line__c();
   quol.Quote__c= parentId;
   }
  
  
 
 	}
}