Velcro test First SandBox/src/objects/Salesforce_Ticket__c.object
<CustomObject>
    <description>For users to enter salesforce help occurencies</description>
    <fields>
        <fullName>Employee_Email__c</fullName>
        <label>Employee Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Employee_First_Name__c</fullName>
        <label>Employee First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Employee_Last_Name__c</fullName>
        <label>Employee Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Salesforce Ticket</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Salesforce Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Velcro test First SandBox/src/classes/SVE_20180413173713_view.cls
global with sharing class SVE_20180413173713_view extends SkyEditor2.SkyEditorPageBaseWithSharing {
	
	public Salesforce_Ticket__c record {get{return (Salesforce_Ticket__c)mainRecord;}}
	public with sharing class CanvasException extends Exception {}

	
	
	{
	setApiVersion(31.0);
	}
	public SVE_20180413173713_view(ApexPages.StandardController controller) {
		super(controller);


		SObjectField f;

		f = Salesforce_Ticket__c.fields.Employee_Email__c;
		f = Salesforce_Ticket__c.fields.Employee_First_Name__c;
		f = Salesforce_Ticket__c.fields.Employee_Last_Name__c;
		f = Salesforce_Ticket__c.fields.Timezone__c;

		List<RecordTypeInfo> recordTypes;
		try {
			mainSObjectType = Salesforce_Ticket__c.SObjectType;
			setPageReferenceFactory(new PageReferenceFactory());
			
			mainQuery = new SkyEditor2.Query('Salesforce_Ticket__c');
			mainQuery.addFieldAsOutput('Name');
			mainQuery.addFieldAsOutput('Employee_Email__c');
			mainQuery.addFieldAsOutput('Employee_First_Name__c');
			mainQuery.addFieldAsOutput('Employee_Last_Name__c');
			mainQuery.addFieldAsOutput('Timezone__c');
			mainQuery.addWhere('Id', mainRecord.Id, SkyEditor2.WhereOperator.Eq)
				.limitRecords(1);
			
			
			
			mode = SkyEditor2.LayoutMode.LayoutFree; 
			
			queryMap = new Map<String, SkyEditor2.Query>();
			SkyEditor2.Query query;
			
			
			p_showHeader = true;
			p_sidebar = true;
			sve_ClassName = 'SVE_20180413173713_view';
			init();
			
			if (record.Id == null) {
				
				saveOldValues();
				
			}

			
			
		}  catch (SkyEditor2.Errors.FieldNotFoundException e) {
			fieldNotFound(e);
		} catch (SkyEditor2.Errors.RecordNotFoundException e) {
			recordNotFound(e);
		} catch (SkyEditor2.ExtenderException e) {
			e.setMessagesToPage();
		}
	}
	

	@TestVisible
		private void sObjectNotFound(SkyEditor2.Errors.SObjectNotFoundException e) {
		SkyEditor2.Messages.addErrorMessage(e.getMessage());
		hidePageBody = true;
	}
	@TestVisible
		private void fieldNotFound(SkyEditor2.Errors.FieldNotFoundException e) {
		SkyEditor2.Messages.addErrorMessage(e.getMessage());
		hidePageBody = true;
	}
	@TestVisible
		private void recordNotFound(SkyEditor2.Errors.RecordNotFoundException e) {
		SkyEditor2.Messages.addErrorMessage(e.getMessage());
		hidePageBody = true;
	}

	with sharing class PageReferenceFactory implements SkyEditor2.PageReferenceFactory.Implementation {
		public PageReference newPageReference(String url) {
			return new PageReference(url);
		}
	}
}